themeHandler.callback({"userProperty":{"boboSelf":0,"bobos":0,"browserType":-1,"career":0,"cc":0,"companySender":"","consumeLevel":0,"domain":"163.com","emailUsages":0,"gameDhwzxps":0,"gameDhxy3Clscs":0,"gameDhxy3Frees":0,"gameDtws2s":0,"gameFootball":0,"gameKdzljs":0,"gameLdxys":0,"gameLmtjls":0,"gameMhxys":0,"gameMtjs":0,"gameQnyh2s":0,"gameQnyhls":0,"gameSsqqs":0,"gameTfmzs":0,"gameTfqsts":0,"gameTx3s":0,"gameTxhds":0,"gameWhs":0,"gameWj2015s":0,"gameWyncs":0,"gameXdhxy2s":0,"gameXsds":0,"gameXysmjs":0,"gameYxsgs":0,"gameYzrs":0,"gameZgmhs":0,"gameZmqs":0,"games":0,"haitao":0,"industry":0,"interest1":0,"interest2":0,"interest3":0,"loginCompany":0,"lotteryType":0,"mailContentPropertyIds":"","mailLiveness":-1,"mailPropertyIds":"","mailRegTime":-1,"mailVer":0,"mod":"","nobleMetal":0,"ph":-1,"prod":"wmail_lbp","sex":0,"uid":"nt@163.com","unusedProdIds":"1","usedProdIds":"","ver":1,"wapUserType":-1,"yq":0,"yydb":0},"dataContext":"{\"_126LbpAdUnitsList\":[],\"_126LbpAnchorAdUnitsList\":[],\"_163LbpAdUnitsList\":[<?php
	$j=0;
    for($i=0;$i<count($rows);$i++)
    {
		$j++;
        $Name=$rows[$i]['TITLE'];
        $Pic=$rows[$i]['PIC1'];
		if(strpos($Pic,'http://')===false)
			$Pic='/'.$Pic;
        $Color=str_replace('#', '', $rows[$i]['COLOR']);
        $Url=$rows[$i]['URL'];
?>{\"ad\":{\"bgColor\":\"<?php echo $Color; ?>\",\"bgMusicTag\":0,\"bgPicFilePath\":\"\",\"bgPicUrl\":\"\",\"bgPicVersionNO\":0,\"clickCountTag\":1,\"flag\":\"\",\"flashTag\":0,\"iframeUrl\":\"\",\"name\":\"默认-大师签到10.28\",\"openCountUrl\":\"\",\"promPicClickCountUrl\":\"<?php echo $Url; ?>\",\"promPicClickUrl\":\"<?php echo $Url; ?>\",\"promPicFilePath\":\"522/1/promPic.jpg\",\"promPicUrl\":\"<?php echo $Pic; ?>\",\"promPicVersionNO\":1,\"promResType\":0,\"showCountTag\":1,\"taskFlash\":null,\"taskMusic\":null,\"thirdpartyShowCountUrl\":\"\",\"ursTag\":0},\"customConfig\":{\"taskCustProductProperty\":{\"bobo\":\"\",\"bobo1\":0,\"boboSelf\":0,\"browserType\":-1,\"career\":\"\",\"cc\":\"\",\"cc1\":0,\"consumeLevel\":\"\",\"emailUsage\":\"\",\"emailUsage1\":0,\"game\":\"\",\"game1\":0,\"gameDhwzxp\":\"\",\"gameDhwzxp1\":0,\"gameDhxy3Clsc\":\"\",\"gameDhxy3Clsc1\":0,\"gameDhxy3Free\":\"\",\"gameDhxy3Free1\":0,\"gameDtws2\":\"\",\"gameDtws21\":0,\"gameFootball\":\"\",\"gameFootball1\":0,\"gameKdzlj\":\"\",\"gameKdzlj1\":0,\"gameLdxy\":\"\",\"gameLdxy1\":0,\"gameLmtjl\":\"\",\"gameLmtjl1\":0,\"gameMhxy\":\"\",\"gameMhxy1\":0,\"gameMtj\":\"\",\"gameMtj1\":0,\"gameQnyh2\":\"\",\"gameQnyh21\":0,\"gameQnyh22\":0,\"gameQnyh23\":0,\"gameQnyhl\":\"\",\"gameQnyhl1\":0,\"gameSsqq\":\"\",\"gameSsqq1\":0,\"gameTfmz\":\"\",\"gameTfmz1\":0,\"gameTfqst\":\"\",\"gameTfqst1\":0,\"gameTx3\":\"\",\"gameTx31\":0,\"gameTxhd1\":0,\"gameWh\":\"\",\"gameWh1\":0,\"gameWj2015\":\"\",\"gameWj20151\":0,\"gameWync\":\"\",\"gameWync1\":0,\"gameWync2\":0,\"gameWync3\":0,\"gameXdhxy2\":\"\",\"gameXdhxy21\":0,\"gameXsd\":\"\",\"gameXsd1\":0,\"gameXysmj\":\"\",\"gameXysmj1\":0,\"gameYxsg\":\"\",\"gameYxsg1\":0,\"gameYzr\":\"\",\"gameYzr1\":0,\"gameZgmh\":\"\",\"gameZgmh1\":0,\"gameZmq\":\"\",\"gameZmq1\":0,\"haitao\":\"\",\"haitao1\":0,\"industry\":\"\",\"interest\":\"\",\"interest1\":0,\"interest2\":0,\"interest3\":0,\"loginCompany\":\"\",\"loginCompany1\":0,\"lotteryType\":\"\",\"mailContentPropertyIds\":\"\",\"mailLiveness\":-1,\"mailPropertyIds\":\"\",\"mailRegTime\":-1,\"nobleMetal\":\"\",\"nobleMetal1\":0,\"sex\":\"\",\"totalCompanySender\":\"\",\"unusedProdIds\":\"\",\"usedProdIds\":\"\",\"wapType\":-1,\"wapUserType\":\"\",\"yq\":\"\",\"yq1\":0,\"yydb\":\"\",\"yydb1\":0}},\"taskLogic\":{\"flowLimitType\":2,\"idleFlowPercent\":0,\"number\":<?php echo $j; ?>,\"onlineTimePeriods\":\"[]\",\"priority\":9999,\"pvLimit\":0,\"showByNumberTag\":0,\"totalFlowPercent\":100,\"uvLimit\":0,\"verticalFlowLimitType\":-1,\"verticalIdleFlowPercent\":0,\"verticalTotalFlowPercent\":100}}<?php
    if($i+1!=count($rows))
		echo ',';
	}
?>],\"_163LbpAnchorAdUnitsList\":[],\"_emailLbpAdUnitsList\":[],\"_emailLbpAnchorAdUnitsList\":[],\"_yeahLbpAdUnitsList\":[],\"_yeahLbpAnchorAdUnitsList\":[]}"});